name: recorder
description: A simple Flutter package for recording and playing audio.
version: 1.0.6
maintainers:
  - name: Hussain Shah
    email: shahjihussain42@gmail.com
repository: https://github.com/shah000/recorder
homepage: https://github.com/shah000/recorder
issue_tracker: https://github.com/shah000/recorder/issues


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.0
  path_provider: ^2.1.1
  record: ^6.1.2
  audioplayers: ^6.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
